Update code to reflect removal of begin pinOCD parameter
https://github.com/Infineon/TLI4970-D050T4-Current-Sensor/commit/39685365ba74f0464fa70e4604c09476a9965832 removed the pinOCD parameter from the begin() definition, but did not remove it from the prototype. This caused compilation to fail:

arduino\libraries\TLI4970-D050T4-Current-Sensor\examples\configEEPROM\configEEPROM.ino: In function 'void setup()':

configEEPROM:14:61: error: no matching function for call to 'Tli4970::begin(SPIClass&, uint8_t, uint8_t)'

   Tli4970CurrentSensor.begin(SPI, (uint8_t)96u, (uint8_t)97u);

                                                             ^